spring.application.name=sistema-cursos

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mariadb://localhost:3306/cursos}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.show_sql=true
